spring:
  servlet:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  jackson:
    mapper:
      default-view-inclusion: true
  datasource:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    url: ${DB_SERVER:jdbc:postgresql://database:5432/postgres}
#     url: jdbc:postgresql://localhost:5432/postgres
  jpa:
      hibernate:
        naming:
          hibernate:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        ddl-auto: validate
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
api:
  jwt:
    secret: SECRET
    expiration: 60000000
    issuer: Issuer
s3:
  bucket: ${S3_BUCKET:spot-test-bucket}