spring:
  servlet:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  jackson:
    mapper:
      default-view-inclusion: true
  datasource:
    username: postgres
    password: postgres
#     url: jdbc:postgresql://database:5432/postgres
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    hibernate:
      show_sql: true
      format_sql: true
      ddl-auto: validate